---

- block:
   - name: Get status of a directory .config/nvim
     ansible.builtin.stat:
      path: "~/.config/nvim/" 
     register: nvim_status
  
   - name: install lazyvim from repository
     ansible.builtin.git:
      repo: "{{ lazyvim_repo }}"
      dest: ~/.config/nvim
      single_branch: 'yes'
      version: main
      force: yes
     when: not nvim_status.stat.exists
     tags:
      - lazyvim
  become: false
  become_user: "{{ local_username }}"
