---

base_productivity_tools:
 - libreoffice
 - mousepad
 - chromium
 - flameshot
 - tmux
 - unzip
 - pwgen
 - wget
 - fish
 - jq
 - kitty
 - kitty-kitten
 - vim
 - stow
 - direnv
 - remmina
 - remmina-plugins-rdp
 - autojump
 - xclip
 - copyq
 - fastfetch
 - glow
 - fzf
 - ranger
 - qemu-system-x86
 - qemu-kvm
 - qemu-img
 - pcmanfm
 - kate
 - cmake
 - krita
 - obs-studio
 - calibre
 - fuse-devel
 - neovim
 - libvirt-daemon-config-network
 - libvirt-daemon-kvm
 - qemu-kvm
 - virt-install
 - virt-manager
 - virt-viewer
 - evince
 - pipx
 - meson 
 - gcc 
 - ninja-build 
 - pkg-config 
 - egl-wayland 
 - egl-wayland-devel 
 - mesa-libEGL-devel 
 - mesa-libEGL 
 - libwayland-egl 
 - libglvnd-devel 
 - libglvnd-core-devel 
 - libglvnd 
 - mesa-libGLES-devel 
 - mesa-libGLES
 - libxkbcommon-devel 
 - libxkbcommon
 - libwayland-client
 - pam-devel 
 - pixman-devel 
 - libgbm-devel
 - libdrm-devel
 - scdoc
 - libavcodec-free-devel 
 - libavfilter-free-devel 
 - libavutil-free-devel
 - turbojpeg-devel	
 - wayland-devel
 - gnutls-devel 
 - jansson-devel
 - moby-engine
